export const USERS_COLLECTION = 'users';
export const PAYMENTS_COLLECTION = 'payments';
export const BUY_PRODUCTS_COLLECTION = 'BUY_PRODUCT';
export const ADS_DATA_COLLECTION = "ADS_DATA"

export const PAYMENT_STORAGE_COLLECTION="PAYMENT"
export const ADS_STORAGE_COLLECTION="ADS_FOLDER"
export const PRODUCT_PAYMENT_STORAGE_COLLECTION="PRODUCT_PAYMENT"